Tests
Runys77/C-Sharp pull request #10
Opened 2022-09-11 17:12 UTC by Runys77

2022-09-17 13:48 UTC, EdgarsSalmins commented on csharp-basics/exercises/Collections/Histogram/Program.cs
> +                if (testScore < 10)
Šim ifu sarakstam ir stipri labāks risinājums.. :) Tu atkārto kodu. :)

2022-09-17 13:49 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hieararchy.Tests/CatTest.cs
> +
lieka tukša rinda

2022-09-17 13:49 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/Hierarchy/Animal.cs
> +        public virtual void Eat(Food food)
Šim nevajadzētu būt abstract?

2022-09-17 13:51 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/ScooterRental.Tests/RentalCompanyTests.cs
> +            //Arange
ja liec šos komentārus tad saliec visur.

2022-09-17 13:51 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/ScooterRental.Tests/RentalCompanyTests.cs
> +            //Arange
ja neliec tad vismaz atdali loģiskos blokus ar tukšām rindām.

2022-09-17 13:52 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/ScooterRental.Tests/RentalCompanyTests.cs
> +        public void HistoryScooters()
metodes nosaukums nenorāda ko tā metode dara.. :) 
MockRentHistory būtu noteikti labāk.

2022-09-17 13:53 UTC, EdgarsSalmins commented on csharp-basics/exercises/Polymorphism/ScooterRental/RentalCompany.cs
> +        {
Šīs metodes saturs varētu būt iznests citā klasē. :) aprēķināt ienākumus nav Rental Company pienākums.

2022-09-17 13:54 UTC, EdgarsSalmins commented on csharp-basics/exercises/TypesAndVariables/ConsoleApp1/Program.cs
> +    internal class Program
kas ir šis?

2022-09-17 13:55 UTC, EdgarsSalmins requested changes
Pārskati komentārus.. 
nav nekas daudz un traks. :) ja vajag palīdzību tad prasi.. :) slikti ka testu PR iekšā viss polimorfisms. :)

2022-09-21 18:02 UTC, Runys77 commented on csharp-basics/exercises/TypesAndVariables/ConsoleApp1/Program.cs
> +    internal class Program
Tas bija DateTime ,kuru uzrasktīju priekš kd un neizņēmu arā

2022-09-22 10:02 UTC, EdgarsSalmins approved these changes

2022-09-22 11:22 UTC, merged