Classes&objects
Runys77/C-Sharp pull request #7
Opened 2022-08-16 11:01 UTC by Runys77

Studentu uzdevums vel nav pabeigts

2022-08-16 19:14 UTC, ausmoons requested changes
Parbaudi visur liekas tuksas rindas

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/BankAccount/Program.cs
> +
Lieka tuksa rinda

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/BankAccount/Bankaccount.cs
> +        public Bankaccount(string accName, decimal balance)
Metodes no pareja parasti atdala ar tuksu rindu

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/ConsoleApp1/Program.cs
> +        public static bool CheckThis(string a, string b)
bool CheckThis? Uz kadu jautajumu atbild?

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/ConsoleApp1/Program.cs
> +
Lieka tuksa rinda

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/ConsoleApp1/Program.cs
> +                if (result = a == b);
Kas notiek ieks if?

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 14/Program.cs
> +            var Input = true;
Uz kadu jautajumu atbild input? Un nosaukumam butu jabut ar mazo burtu

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 3/Fuel Gauge.cs
> +
Liekas tuksas rindas

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 3/Odometr .cs
> +
Daudz lieku tuksu rindu

2022-08-16 19:14 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 3/Odometr .cs
> +        public FuelGauge mFuelGauge;
ja public, tad ar lielo burtu

2022-08-28 08:43 UTC, Runys77 commented on csharp-basics/exercises/ClassesAndObjects/ConsoleApp1/Program.cs
> +
šis uzdevums neattiecās uz šo mapi , netīšām viņu pievienoju

2022-08-28 08:45 UTC, Runys77 commented on csharp-basics/exercises/ClassesAndObjects/ConsoleApp1/Program.cs
> +
Tas bija uzdevums , ko Edgars iedeva lekcijā un sāku viņu rakstīt Clases mapē, bet pirms nodošanas aizmirsu izdzēst

2022-08-28 08:50 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/ConsoleApp1/Program.cs
> +
Tad izņem ārā

2022-08-28 09:18 UTC, ausmoons approved these changes

2022-09-22 11:23 UTC, merged